[package]

name = "skia-sys"
version = "0.20130412.3"
authors = ["The Skia Project Developers and The Servo Project Developers"]
description = "2D graphic library for drawing Text, Geometries, and Images. FFI bindings only."
license = "BSD-3-Clause"
repository ="https://github.com/servo/skia/"
homepage = "https://skia.org/"
links = "skia"
build = "build.rs"
exclude = [
    "experimental/*",
    "expectations/*",
    "platform_tools/android/bin/*",
    "tools/*",
    "tests/*",
]

[lib]
name = "skia_sys"

[dependencies]
libc = "0.2"
